title: Application Added to Google Workspace Domain
id: 785a404b-75aa-4ffd-8be5-3334a5a544dd
status: stable
level: medium
description: 'Detects when a Google marketplace application is added to the Google
  Workspace domain. An adversary may add a malicious

  application to an organization’s Google Workspace domain in order to maintain a
  presence in their target’s organization

  and steal data.'
author: Elastic (converted by SIEMLess)
date: '2020-11-17'
modified: '2024-09-23'
logsource:
  product: windows
  category: process_creation
detection:
  selection:
    event_dataset: google_workspace.admin
    event_provider: admin
    event_category: iam
    event_action: ADD_APPLICATION
  condition: selection
tags:
- attack.persistence
references:
- https://support.google.com/a/answer/6328701?hl=en#
- https://www.elastic.co/security-labs/google-workspace-attack-surface-part-one
- https://www.elastic.co/security-labs/google-workspace-attack-surface-part-two
falsepositives:
- "    Applications can be added to a Google Workspace domain by system administrators.\
  \ Verify that the configuration\n    change was expected. Exceptions can be added\
  \ to this rule to filter expected behavior.\n    "
