title: GCP Storage Bucket Configuration Modification
id: 97359fd8-757d-4b1d-9af1-ef29e4a8680e
status: stable
level: medium
description: 'Identifies when the configuration is modified for a storage bucket in
  Google Cloud Platform (GCP). An adversary may

  modify the configuration of a storage bucket in order to weaken the security controls
  of their target''s environment.'
author: Elastic (converted by SIEMLess)
date: '2020-09-22'
modified: '2025-01-15'
logsource:
  product: windows
  category: process_creation
detection:
  selection:
    event_dataset: gcp.audit
    event_action: storage.buckets.update
    event_outcome: success
  condition: selection
tags:
- attack.defense_evasion
- attack.t1578
references:
- https://cloud.google.com/storage/docs/key-terms#buckets
falsepositives:
- "    Storage bucket configuration may be modified by system administrators. Verify\
  \ that the configuration change was\n    expected. Exceptions can be added to this\
  \ rule to filter expected behavior.\n    "
