title: GitHub Protected Branch Settings Changed
id: 07639887-da3a-4fbf-9532-8ce748ff8c50
status: stable
level: medium
description: 'This rule detects setting modifications for protected branches of a
  GitHub repository. Branch protection rules can be

  used to enforce certain workflows or requirements before a contributor can push
  changes to a branch in your repository.

  Changes to these protected branch settings should be investigated and verified as
  legitimate activity. Unauthorized

  changes could be used to lower your organization''s security posture and leave you
  exposed for future attacks.'
author: Elastic (converted by SIEMLess)
date: '2023-08-29'
modified: '2025-03-20'
logsource:
  product: windows
  category: process_creation
detection:
  selection:
    event_dataset: github.audit
    github_category: protected_branch
    event_type: change
  condition: selection
tags:
- attack.defense_evasion
- attack.t1562
- attack.t1562.001
