title: Kubernetes Sensitive Configuration File Activity
id: 0fe2290a-2664-4c9c-8263-b88904f12f0d
status: stable
level: medium
description: 'This rule detects the creation or modification of sensitive Kubernetes
  configuration files on Linux systems. These files

  include Kubernetes manifests, PKI files, and configuration files that are critical
  for the operation of Kubernetes clusters.

  Monitoring these files helps identify potential unauthorized changes or misconfigurations
  that could lead to security

  vulnerabilities in Kubernetes environments. Attackers may attempt to modify these
  files to gain persistence or to

  deploy malicious containers within the Kubernetes cluster.'
author: Elastic (converted by SIEMLess)
date: '2025-06-26'
modified: '2025-07-07'
logsource:
  product: linux
  category: file_event
detection:
  selection:
    host_os_type: linux
  condition: selection
tags:
- attack.persistence
- attack.t1053
- attack.t1543.005
- attack.t1053.007
- attack.t1543
