title: Kubeconfig File Creation or Modification
id: b11116fd-023c-4718-aeb8-fa9d283fc53b
status: stable
level: medium
description: 'The kubeconfig file is a critical component in Kubernetes environments,
  containing configuration

  details for accessing and managing Kubernetes clusters. Attackers may attempt to
  get access to,

  create or modify kubeconfig files to gain unauthorized initial access to Kubernetes
  clusters or

  move laterally within the cluster.'
author: Elastic (converted by SIEMLess)
date: '2025-06-17'
modified: '2025-07-07'
logsource:
  product: linux
  category: file_event
detection:
  selection:
    host_os_type: linux
    process_name: sed
  condition: selection
tags:
- attack.defense_evasion
- attack.initial_access
- attack.lateral_movement
- attack.t1550
- attack.t1078
references:
- https://kubernetes-threat-matrix.redguard.ch/initial-access/kubeconfig-file/
- https://kubenomicon.com/Initial_access/Kubeconfig_file.html
