title: Kubeconfig File Discovery
id: 9a6f5d74-c7e7-4a8b-945e-462c102daee4
status: stable
level: low
description: 'The kubeconfig file is a critical component in Kubernetes environments,
  containing configuration

  details for accessing and managing Kubernetes clusters. Attackers may attempt to
  get access to,

  create, or modify kubeconfig files to gain unauthorized initial access to Kubernetes
  clusters or

  move laterally within the cluster. This rule detects process discovery executions
  that involve

  kubeconfig files, particularly those executed from common shell environments or
  world-writeable

  directories.'
author: Elastic (converted by SIEMLess)
date: '2025-06-17'
modified: '2025-07-07'
logsource:
  product: linux
  category: process_creation
detection:
  selection:
    host_os_type: linux
    event_type: start
    event_action: exec
  condition: selection
tags:
- attack.discovery
- attack.t1613
references:
- https://kubernetes-threat-matrix.redguard.ch/initial-access/kubeconfig-file/
- https://kubenomicon.com/Initial_access/Kubeconfig_file.html
