title: Microsoft Build Engine Started by an Office Application
id: c5dc3223-13a2-44a2-946c-e9dc0aa0449c
status: stable
level: high
description: 'An instance of MSBuild, the Microsoft Build Engine, was started by Excel
  or Word. This is unusual behavior for the Build

  Engine and could have been caused by an Excel or Word document executing a malicious
  script payload.'
author: Elastic (converted by SIEMLess)
date: '2020-03-25'
modified: '2025-03-20'
logsource:
  product: windows
  category: process_creation
detection:
  selection:
    host_os_type: windows
    event_type: start
    process_parent_name|contains:
    - eqnedt32.exe
    - excel.exe
    - fltldr.exe
    - msaccess.exe
    - mspub.exe
    - outlook.exe
    - powerpnt.exe
    - winword.exe
  condition: selection
tags:
- attack.defense_evasion
- attack.execution
- attack.t1127.001
- attack.t1127
references:
- https://blog.talosintelligence.com/2020/02/building-bypass-with-msbuild.html
falsepositives:
- "    The Build Engine is commonly used by Windows developers but use by non-engineers\
  \ is unusual. It is quite unusual for\n    this program to be started by an Office\
  \ application like Word or Excel.\n    "
