title: Microsoft 365 Teams Custom Application Interaction Allowed
id: bbd1a775-8267-41fa-9232-20e5582596ac
status: stable
level: medium
description: 'Identifies when custom applications are allowed in Microsoft Teams.
  If an organization requires applications other than

  those available in the Teams app store, custom applications can be developed as
  packages and uploaded. An adversary may

  abuse this behavior to establish persistence in an environment.'
author: Elastic (converted by SIEMLess)
date: '2020-11-30'
modified: '2025-09-30'
logsource:
  product: windows
  category: process_creation
detection:
  selection:
    event_dataset: o365.audit
    event_provider: MicrosoftTeams
    event_category: web
    event_action: TeamsTenantSettingChanged
    o365_audit_Name: Allow
    o365_audit_NewValue: 'True'
    event_outcome: success
  condition: selection
tags:
- attack.defense_evasion
- attack.t1562
references:
- https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/apps-upload
falsepositives:
- "    Custom applications may be allowed by a system or network administrator. Verify\
  \ that the configuration change was\n    expected. Exceptions can be added to this\
  \ rule to filter expected behavior.\n    "
