title: Modification of Boot Configuration
id: 69c251fb-a5d6-4035-b5ec-40438bd829ff
status: stable
level: low
description: 'Identifies use of bcdedit.exe to delete boot configuration data. This
  tactic is sometimes used as by malware or an

  attacker as a destructive technique.'
author: Elastic (converted by SIEMLess)
date: '2020-03-16'
modified: '2025-03-20'
logsource:
  product: windows
  category: process_creation
detection:
  selection:
    host_os_type: windows
    event_type: start
    process_pe_original_file_name: bcdedit.exe
  condition: selection
tags:
- attack.impact
- attack.t1490
