title: Modification of Safari Settings via Defaults Command
id: 6482255d-f468-45ea-a5b3-d3a7de1331ae
status: stable
level: medium
description: 'Identifies changes to the Safari configuration using the built-in defaults
  command. Adversaries may attempt to enable or

  disable certain Safari settings, such as enabling JavaScript from Apple Events to
  ease in the hijacking of the users

  browser.'
author: Elastic (converted by SIEMLess)
date: '2021-01-14'
modified: '2025-03-18'
logsource:
  product: macos
  category: process_creation
detection:
  selection:
    host_os_type: macos
    process_name: defaults
  condition: selection
tags:
- attack.defense_evasion
- attack.t1562
- attack.t1562.001
references:
- https://objectivebythesea.com/v2/talks/OBTS_v2_Zohar.pdf
