title: Potential Application Shimming via Sdbinst
id: fd4a992d-6130-4802-9ff8-829b89ae801f
status: stable
level: low
description: 'The Application Shim was created to allow for backward compatibility
  of software as the operating system codebase

  changes over time. This Windows functionality has been abused by attackers to stealthily
  gain persistence and arbitrary

  code execution in legitimate Windows processes.'
author: Elastic (converted by SIEMLess)
date: '2020-02-18'
modified: '2025-03-20'
logsource:
  product: windows
  category: process_creation
detection:
  selection:
    host_os_type: windows
    event_type: start
  condition: selection
tags:
- attack.persistence
- attack.privilege_escalation
- attack.t1546.011
- attack.t1546
