title: Script Execution via Microsoft HTML Application
id: 181f6b23-3799-445e-9589-0018328a9e46
status: stable
level: high
description: 'Identifies the execution of scripts via HTML applications using Windows
  utilities rundll32.exe or mshta.exe. Adversaries

  may bypass process and/or signature-based defenses by proxying execution of malicious
  content with signed binaries.'
author: Elastic (converted by SIEMLess)
date: '2020-09-09'
modified: '2025-09-01'
logsource:
  product: windows
  category: process_creation
detection:
  selection:
    host_os_type: windows
    event_type: start
    process_name|contains:
    - rundll32.exe
    - mshta.exe
    process_command_line|contains:
    - '*.hta*'
    - '*.htm*'
    - -Embedding
    process_args|contains:
    - ?:\\Users\\*\\Temp\\7z*
    - ?:\\Users\\*\\Temp\\Rar$*
    - ?:\\Users\\*\\Temp\\Temp?_*
    - ?:\\Users\\*\\Temp\\BNZ.*
    process_command_line|endswith: \\Users\\*\\Downloads\\*.hta*
  condition: selection
tags:
- attack.defense_evasion
- attack.t1218.011
- attack.t1218
- attack.t1218.005
