title: SELinux Configuration Creation or Renaming
id: 7b981906-86b7-4544-8033-c30ec6eb45fc
status: stable
level: low
description: 'This rule detects the creation or renaming of the SELinux configuration
  file. SELinux is a security module that provides

  access control security policies. Modifications to the SELinux configuration file
  may indicate an attempt to impair

  defenses by disabling or modifying security tools.'
author: Elastic (converted by SIEMLess)
date: '2024-08-28'
modified: '2025-07-02'
logsource:
  product: linux
  category: file_event
detection:
  selection:
    host_os_type: linux
  condition: selection
tags:
- attack.defense_evasion
- attack.t1562
- attack.t1562.001
