title: Sublime Plugin or Application Script Modification
id: 88817a33-60d3-411f-ba79-7c905d865b2a
status: stable
level: low
description: 'Adversaries may create or modify the Sublime application plugins or
  scripts to execute a malicious payload each time the

  Sublime application is started.'
author: Elastic (converted by SIEMLess)
date: '2020-12-23'
modified: '2025-03-18'
logsource:
  product: macos
  category: file_event
detection:
  selection:
    host_os_type: macos
    event_action: modification
    file_extension: py
  condition: selection
tags:
- attack.persistence
- attack.t1554
references:
- https://posts.specterops.io/persistent-jxa-66e1c3cd1cf5
