title: Suspicious Microsoft HTML Application Child Process
id: 48e60a73-08e8-42aa-8f51-4ed92c64dbea
status: stable
level: high
description: 'Identifies Mshta.exe spawning a suspicious child process. This may indicate
  adversarial activity, as Mshta is often

  leveraged by adversaries to execute malicious scripts and evade detection.'
author: Elastic (converted by SIEMLess)
date: '2025-08-19'
modified: '2025-08-19'
logsource:
  product: windows
  category: process_creation
detection:
  selection:
    host_os_type: windows
    event_type: start
    process_name|contains:
    - cmd.exe
    - powershell.exe
    - certutil.exe
    - bitsadmin.exe
    - curl.exe
    - msiexec.exe
    - schtasks.exe
    - reg.exe
    - wscript.exe
    - rundll32.exe
    process_executable|contains:
    - C:\\Users\\*\\*.exe
    - \\Device\\HarddiskVolume*\\Users\\*\\*.exe
  condition: selection
tags:
- attack.defense_evasion
- attack.t1218
- attack.t1218.005
references:
- https://lolbas-project.github.io/lolbas/Binaries/Mshta/
