title: User Added as Owner for Azure Application
id: 774f5e28-7b75-4a58-b94e-41bf060fdd86
status: stable
level: low
description: 'Identifies when a user is added as an owner for an Azure application.
  An adversary may add a user account as an owner

  for an Azure application in order to grant additional permissions and modify the
  application''s configuration using

  another account.'
author: Elastic (converted by SIEMLess)
date: '2020-08-20'
modified: '2025-09-30'
logsource:
  product: windows
  category: process_creation
detection:
  selection:
    event_dataset: azure.auditlogs
    azure_auditlogs_operation_name: Add
    event_outcome: (Success
  condition: selection
tags:
- attack.persistence
- attack.credential_access
- attack.t1528
- attack.t1098
