title: Changes to Application Ownership
id: 38f03e7a-eb3d-5b63-a49e-30ff0953c831
status: stable
level: medium
description: |
  'Detects changes to the ownership of an appplicaiton.   Monitor these changes to make sure that they were authorized.   Ref: https://learn.microsoft.com/en-gb/entra/architecture/security-operations-applications#new-owner'
author: Microsoft Security Research
logsource:
  product: azure
detection:
  selection:
    Category: ApplicationManagement
    OperationName: Add owner to application
  condition: selection
tags:
  - attack.t1078.004
custom_attributes:
  original_rule_id: cc5780ce-3245-4bba-8bc1-e9048c2257ce
  source_format: azure_kql