title: Change To Safe Mode With Network Config
id: c0b0d2d2-9394-5d93-b1cb-f18f161a848d
status: stable
level: high
description: |
  The following analytic detects the execution of a suspicious `bcdedit` command that configures a host to boot in safe mode with network support. It leverages data from Endpoint Detection and Response (EDR) agents, focusing on command-line executions involving `bcdedit.exe` with specific parameters. This activity is significant because it is a known technique used by BlackMatter ransomware to force a compromised host into safe mode for continued encryption. If confirmed malicious, this could allo
author: Teoderick Contreras, Splunk
logsource:
  product: splunk
  category: network_connection
detection:
  selection:
    process:
      - '*/set*'
      - '*{current}*'
      - '*safeboot*'
      - '*network*'
  condition: selection
tags:
  - attack.t1490
references:
  - https://news.sophos.com/en-us/2021/08/09/blackmatter-ransomware-emerges-from-the-shadow-of-darkside/
custom_attributes:
  original_rule_id: 81f1dce0-0f18-11ec-a5d7-acde48001122
  source_format: splunk_spl