title: Cisco ASA - Logging Filters Configuration Tampering
id: c738d4bb-399d-5cea-8f5b-3221f51d8136
status: stable
level: medium
description: |
  This analytic detects tampering with logging filter configurations on Cisco ASA devices via CLI or ASDM. Adversaries may reduce logging levels or disable specific log categories to evade detection, hide their activities, or prevent security monitoring systems from capturing evidence of their actions. By lowering logging verbosity, attackers can operate with reduced visibility to security teams. The detection monitors for logging configuration commands (message ID 111008 or 111010) that modify lo
author: Nasreddine Bencherchali, Splunk
logsource:
  product: splunk
detection:
  selection:
    command:
      - '*notifications*'
      - '*informational*'
      - '*debugging*'
      - '* 5*'
      - '* 6*'
      - '* 7*'
    message_id:
      - 111008
      - 111010
  condition: selection
tags:
  - attack.t1562
references:
  - https://www.cisco.com/c/en/us/td/docs/security/asa/asa-cli-reference/I-R/asa-command-ref-I-R/m_log-lz.html
custom_attributes:
  original_rule_id: b87b48a8-6d1a-4280-9cf1-16a950dbf901
  source_format: splunk_spl