title: Detect Prohibited Applications Spawning cmd exe
id: 50aef4ee-b290-5d24-8331-1ce8bdd90aa9
status: stable
level: low
description: |
  The following analytic detects executions of cmd.exe spawned by processes that are commonly abused by attackers and do not typically launch cmd.exe. It leverages data from Endpoint Detection and Response (EDR) agents, focusing on process GUID, process name, parent process, and command-line executions. This activity is significant because it may indicate an attempt to execute unauthorized commands or scripts, often a precursor to further malicious actions. If confirmed malicious, this behavior co
author: Bhavin Patel, Splunk
logsource:
  product: splunk
detection:
  selection:
    parent_process_name: '*'
  condition: selection
tags:
  - attack.t1059.003
custom_attributes:
  original_rule_id: dcfd6b40-42f9-469d-a433-2e53f7486664
  source_format: splunk_spl