title: GitHub Organizations Disable Dependabot
id: 7039c32b-d967-5ca8-ac80-4c649d793470
status: stable
level: medium
description: |
  The following analytic detects when a user disables Dependabot security features within a GitHub repository. Dependabot helps automatically identify and fix security vulnerabilities in dependencies. The detection monitors GitHub Enterprise logs for configuration changes that disable Dependabot functionality. This behavior could indicate an attacker attempting to prevent the automatic detection of vulnerable dependencies, which would allow them to exploit known vulnerabilities that would otherwis
author: Patrick Bareiss, Splunk
logsource:
  product: github
detection:
  selection:
    _spl_reference: true
  condition: selection
tags:
  - attack.t1562.001
  - attack.t1195
references:
  - https://splunk.github.io/splunk-add-on-for-github-audit-log-monitoring/Install/
  - https://www.googlecloudcommunity.com/gc/Community-Blog/Monitoring-for-Suspicious-GitHub-Activity-with-Google-Security/ba-p/763610
custom_attributes:
  original_rule_id: 69078d8c-0de6-45de-bb00-14e78e042fd6
  source_format: splunk_spl