title: GitHub Enterprise Disable Dependabot
id: f73e4b44-ff89-5f74-9a15-2013099d4302
status: stable
level: medium
description: |
  The following analytic detects when a user disables Dependabot security features within a GitHub repository. Dependabot helps automatically identify and fix security vulnerabilities in dependencies. The detection monitors GitHub Enterprise logs for configuration changes that disable Dependabot functionality. This behavior could indicate an attacker attempting to prevent the automatic detection of vulnerable dependencies, which would allow them to exploit known vulnerabilities that would otherwis
author: Patrick Bareiss, Splunk
logsource:
  product: github
detection:
  selection:
    _spl_reference: true
  condition: selection
tags:
  - attack.t1562.001
  - attack.t1195
references:
  - https://www.googlecloudcommunity.com/gc/Community-Blog/Monitoring-for-Suspicious-GitHub-Activity-with-Google-Security/ba-p/763610
  - https://docs.github.com/en/enterprise-cloud@latest/admin/monitoring-activity-in-your-enterprise/reviewing-audit-logs-for-your-enterprise/streaming-the-audit-log-for-your-enterprise#setting-up-streaming-to-splunk
custom_attributes:
  original_rule_id: 787dd1c1-eb3a-4a31-8e8c-2ad24b214bc8
  source_format: splunk_spl