title: Linux Auditd At Application Execution
id: 5549ec23-b825-5636-869b-8dbdeb5c56a1
status: stable
level: medium
description: |
  The following analytic detects the execution of the "At" application in Linux, which can be used by attackers to create persistence entries on a compromised host. This detection leverages data from Endpoint Detection and Response (EDR) agents, focusing on process names and parent process names associated with "at" or "atd". This activity is significant because the "At" application can be exploited to maintain unauthorized access or deliver additional malicious payloads. If confirmed malicious, t
author: Teoderick Contreras, Splunk
logsource:
  product: linux
  category: process_creation
detection:
  selection:
    type: SYSCALL
    comm:
      - at
      - atd
    exe:
      - /usr/bin/at
      - /usr/bin/atd
    uid:
      - daemon
  condition: selection
tags:
  - attack.t1053.002
references:
  - https://attack.mitre.org/techniques/T1053/001/
  - https://www.linkedin.com/pulse/getting-attacker-ip-address-from-malicious-linux-job-craig-rowland/
custom_attributes:
  original_rule_id: 9f306e0a-1c36-469e-8892-968ca12470dd
  source_format: splunk_spl