title: Linux Ingress Tool Transfer Hunting
id: 65e56f86-729b-5013-a021-f308cfa90e5d
status: stable
level: low
description: |
  The following analytic detects the use of 'curl' and 'wget' commands within a Linux environment. It leverages data from Endpoint Detection and Response (EDR) agents, focusing on process names, user information, and command-line executions. This activity is significant as 'curl' and 'wget' are commonly used for downloading files, which can indicate potential ingress of malicious tools. If confirmed malicious, this activity could lead to unauthorized code execution, data exfiltration, or further c
author: Michael Haag, Splunk
logsource:
  product: linux
detection:
  selection:
    process_name: curl
  condition: selection
tags:
  - attack.t1105
references:
  - https://gtfobins.github.io/gtfobins/curl/
  - https://curl.se/docs/manpage.html#-I
  - https://gtfobins.github.io/gtfobins/curl/
  - https://github.com/rapid7/metasploit-framework/search?q=curl
custom_attributes:
  original_rule_id: 52fd468b-cb6d-48f5-b16a-92f1c9bb10cf
  source_format: splunk_spl