title: Linux Ingress Tool Transfer with Curl
id: 18981c7e-3dd8-5308-b5bd-5c7b7e264b73
status: stable
level: medium
description: |
  The following analytic detects the use of the curl command with specific switches (-O, -sO, -ksO, --output) commonly used to download remote scripts or binaries. This detection leverages data from Endpoint Detection and Response (EDR) agents, focusing on process names and command-line arguments. This activity is significant as it may indicate an attempt to download and execute potentially malicious files, often used in initial stages of an attack. If confirmed malicious, this could lead to unaut
author: Michael Haag, Splunk
logsource:
  product: linux
detection:
  selection:
    process_name: curl
  condition: selection
tags:
  - attack.t1105
references:
  - https://gtfobins.github.io/gtfobins/curl/
  - https://curl.se/docs/manpage.html#-I
  - https://gtfobins.github.io/gtfobins/curl/
  - https://github.com/rapid7/metasploit-framework/search?q=curl
custom_attributes:
  original_rule_id: 8c1de57d-abc1-4b41-a727-a7a8fc5e0857
  source_format: splunk_spl