title: O365 Application Registration Owner Added
id: 6609b429-d410-5f99-a21f-9a154df4f21c
status: stable
level: high
description: |
  The following analytic identifies instances where a new owner is assigned to an application registration within an Azure AD and Office 365 tenant. It leverages O365 audit logs, specifically events related to changes in owner assignments within the AzureActiveDirectory workload. This activity is significant because assigning a new owner to an application registration can grant significant control over the application's configuration, permissions, and behavior. If confirmed malicious, an attacker 
author: Mauricio Velazco, Splunk
logsource:
  product: azure
detection:
  selection:
    operation: Add owner to application.
    workload: AzureActiveDirectory
  condition: selection
tags:
  - attack.t1098
references:
  - https://attack.mitre.org/techniques/T1098/
  - https://learn.microsoft.com/en-us/azure/active-directory/manage-apps/overview-assign-app-owners
custom_attributes:
  original_rule_id: c068d53f-6aaa-4558-8011-3734df878266
  source_format: splunk_spl