title: Okta Multiple Failed Requests to Access Applications
id: 9c060efd-308b-5619-8d82-f43692cbd0c0
status: experimental
level: low
description: |
  The following analytic detects multiple failed attempts to access applications in Okta, potentially indicating the reuse of a stolen web session cookie. It leverages Okta logs to evaluate policy and SSO events, aggregating data by user, session, and IP. The detection triggers when more than half of the app sign-on attempts are unsuccessful across multiple applications. This activity is significant as it may indicate an attempt to bypass authentication mechanisms. If confirmed malicious, it could
author: John Murphy, Okta, Michael Haag, Splunk
logsource:
  product: okta
detection:
  selection:
    eventtype:
      - policy.evaluate_sign_on
      - user.authentication.sso
    severity: HIGH
    mitre_technique_id: T1538
    description: actor.alternateId
    type: AppInstance
  condition: selection
tags:
  - attack.t1550.004
  - attack.t1538
references:
  - https://attack.mitre.org/techniques/T1538
  - https://attack.mitre.org/techniques/T1550/004
custom_attributes:
  original_rule_id: 1c21fed1-7000-4a2e-9105-5aaafa437247
  source_format: splunk_spl