title: Windows Unusual FileZilla XML Config Access
id: 453d17cf-f662-5433-8460-e4871e1276dc
status: stable
level: medium
description: |
  The following analytic identifies processes accessing FileZilla XML config files such as recentservers.xml and sitemanager.xml. It leverages Windows Security Event logs, specifically monitoring EventCode 4663, which tracks object access events. This activity is significant because it can indicate unauthorized access or manipulation of sensitive configuration files used by FileZilla, a popular FTP client. If confirmed malicious, this could lead to data exfiltration, credential theft, or further c
author: Teoderick Contreras, Splunk
logsource:
  product: windows
  category: file_event
detection:
  selection:
    eventcode: 4663
    processname:
      - 'C:\\Program Files\\FileZilla FTP Client\\filezilla.exe'
      - 'C:\Program Files (x86'
    file_path:
      - '*FileZilla\\recentservers.xml*'
      - '*FileZilla\\sitemanager.xml*'
  condition: selection
tags:
  - attack.t1552.001
references:
  - https://www.trendmicro.com/en_us/research/18/k/trickbot-shows-off-new-trick-password-grabber-module.html
custom_attributes:
  original_rule_id: 47dc0426-cbe4-4253-8b86-1a983c3f9951
  source_format: splunk_spl