title: Windows Defender ASR or Threat Configuration Tamper
id: efb5a380-34a2-5fb3-9af5-b469091080b2
status: stable
level: high
description: |
  The following analytic detects the use of commands to disable Attack Surface Reduction (ASR) rules or change threat default actions in Windows Defender. It leverages data from Endpoint Detection and Response (EDR) agents, focusing on command-line executions involving "Add-MpPreference" or "Set-MpPreference". This activity is significant because adversaries often use it to bypass Windows Defender, allowing malicious code to execute undetected. If confirmed malicious, this behavior could enable at
author: Nasreddine Bencherchali, Splunk
logsource:
  product: windows
detection:
  selection:
    process:
      - '*Allow*'
      - '*NoAction*'
      - '*Disabled*'
      - '*_Actions 6*'
      - '*_Actions 9*'
      - '*_Actions 0*'
  condition: selection
tags:
  - attack.t1562.001
references:
  - https://learn.microsoft.com/en-us/powershell/module/defender/set-mppreference?view=windowsserver2025-ps#-attacksurfacereductionrules-actions
  - https://www.virustotal.com/gui/file/7e805617c313ec2fb59d86719c827074cb7dfbf8f0aa18194ac1ffe6c21c8967/behavior
custom_attributes:
  original_rule_id: d0c07718-19d1-4de2-aea9-e0ffff0ed986
  source_format: splunk_spl