title: Windows Ingress Tool Transfer Using Explorer
id: 3d52b20e-95fb-55dd-9db2-243aa5feb4b9
status: stable
level: medium
description: |
  The following analytic identifies instances where the Windows Explorer process (explorer.exe) is executed with a URL in its command line. This detection leverages data from Endpoint Detection and Response (EDR) agents, focusing on process execution logs. This activity is significant because adversaries, such as those using DCRat malware, may abuse explorer.exe to open URLs with the default browser, which is an uncommon and suspicious behavior. If confirmed malicious, this technique could allow a
author: Teoderick Contreras, Splunk
logsource:
  product: windows
detection:
  selection:
    parent_process_name:
      - userinit.exe
      - svchost.exe
    process:
      - '* http://*'
      - '* https://*'
  condition: selection
tags:
  - attack.t1105
references:
  - https://www.mandiant.com/resources/analyzing-dark-crystal-rat-backdoor
custom_attributes:
  original_rule_id: 76753bab-f116-4ea3-8fb9-89b638be58a9
  source_format: splunk_spl