title: Windows AppLocker Rare Application Launch Detection
id: dbfeb6c2-3af6-5f6e-a5fa-b9ca8e3b26a4
status: stable
level: low
description: |
  The following analytic detects the launch of rarely used applications within the environment, which may indicate the use of potentially malicious software or tools by attackers. It leverages Windows AppLocker event logs, aggregating application launch counts over time and flagging those that significantly deviate from the norm. This behavior is significant as it helps identify unusual application activity that could signal a security threat. If confirmed malicious, this activity could allow atta
author: Michael Haag, Splunk
logsource:
  product: windows
detection:
  selection:
    input: UserData_Xml
  condition: selection
tags:
  - attack.t1218
references:
  - https://learn.microsoft.com/en-us/windows/security/application-security/application-control/windows-defender-application-control/applocker/using-event-viewer-with-applocker
  - https://learn.microsoft.com/en-us/windows/security/application-security/application-control/windows-defender-application-control/operations/querying-application-control-events-centrally-using-advanced-hunting
custom_attributes:
  original_rule_id: 9556f7b7-285f-4f18-8eeb-963d989f9d27
  source_format: splunk_spl