title: Cisco IOS router configuration changed.
id: 877947bf-6060-585e-afd5-067e86291ed3
status: stable
level: low
description: Cisco IOS router configuration changed.
author: Wazuh, Inc.
logsource:
  product: wazuh
detection:
  selection:
    message|exists: true
  condition: selection

# Sigma+ Extensions (for advanced detection)
extensions:
  parent_rule: wazuh-4715
references:
  - https://github.com/wazuh/wazuh
  - https://documentation.wazuh.com/current/user-manual/ruleset/custom.html
custom_attributes:
  wazuh_rule_id: wazuh-4721
  wazuh_level: 3