title: DNS configuration error.
id: 0829be84-5df6-56d5-b6de-e13fdb6a7aaa
status: stable
level: low
description: DNS configuration error.
author: Wazuh, Inc.
logsource:
  product: wazuh
detection:
  selection:
    message|contains: refused notify from non-master
  condition: selection

# Sigma+ Extensions (for advanced detection)
extensions:
  parent_rule: wazuh-12100
references:
  - https://github.com/wazuh/wazuh
  - https://documentation.wazuh.com/current/user-manual/ruleset/custom.html
custom_attributes:
  wazuh_rule_id: wazuh-12106
  wazuh_level: 4