title: 'Docker: Configuration of container $(docker.Actor.Attributes.name) updated'
id: d314bc40-3b1b-51e7-bdf9-278ae279a912
status: stable
level: low
description: 'Docker: Configuration of container $(docker.Actor.Attributes.name) updated'
author: Wazuh, Inc.
logsource:
  product: wazuh
detection:
  selection:
    docker.status: ^update$
  condition: selection

# Sigma+ Extensions (for advanced detection)
extensions:
  parent_rule: wazuh-87900
references:
  - https://github.com/wazuh/wazuh
  - https://documentation.wazuh.com/current/user-manual/ruleset/custom.html
custom_attributes:
  wazuh_rule_id: wazuh-87925
  wazuh_level: 3