title: 'Fortigate: Configuration changed.'
id: 6d28e9ec-ae7f-58fb-a0dd-8b24fa5eb3fd
status: stable
level: medium
description: 'Fortigate: Configuration changed.'
author: Wazuh, Inc.
logsource:
  product: wazuh
detection:
  selection:
    message|contains: Configuration is changed in the admin session
  condition: selection

# Sigma+ Extensions (for advanced detection)
extensions:
  parent_rule: wazuh-81603
references:
  - https://github.com/wazuh/wazuh
  - https://documentation.wazuh.com/current/user-manual/ruleset/custom.html
custom_attributes:
  wazuh_rule_id: wazuh-81608
  wazuh_level: 7