title: 'FTPD: Reverse lookup error (bad ISP config).'
id: a52c26d3-f861-5678-916f-5f50ffacfadc
status: stable
level: low
description: 'FTPD: Reverse lookup error (bad ISP config).'
author: Wazuh, Inc.
logsource:
  product: wazuh
detection:
  selection:
    message|contains:
      - 'warning: can''t verify hostname:'
      - 'gethostbyaddr:'
  condition: selection

# Sigma+ Extensions (for advanced detection)
extensions:
  parent_rule: wazuh-11100
references:
  - https://github.com/wazuh/wazuh
  - https://documentation.wazuh.com/current/user-manual/ruleset/custom.html
custom_attributes:
  wazuh_rule_id: wazuh-11108
  wazuh_level: 5