title: 'Inspect: Connection was subject to a configured protections.'
id: 37321033-d04f-5f32-9cb1-892dd72d41dd
status: stable
level: low
description: 'Inspect: Connection was subject to a configured protections.'
author: Wazuh, Inc.
logsource:
  product: wazuh
detection:
  selection:
    fw_action: Inspect
  condition: selection

# Sigma+ Extensions (for advanced detection)
extensions:
  parent_rule: wazuh-64220
references:
  - https://github.com/wazuh/wazuh
  - https://documentation.wazuh.com/current/user-manual/ruleset/custom.html
custom_attributes:
  wazuh_rule_id: wazuh-64236
  wazuh_level: 4