title: 'Netscaler: ICA application launch has started'
id: 2ac58fd5-2942-52f3-8d57-0dbaa8f0315d
status: stable
level: informational
description: 'Netscaler: ICA application launch has started'
author: Wazuh, Inc.
logsource:
  product: wazuh
detection:
  selection:
    message|contains: SSLVPN ICASTART
  condition: selection

# Sigma+ Extensions (for advanced detection)
extensions:
  parent_rule: wazuh-80100
references:
  - https://github.com/wazuh/wazuh
  - https://documentation.wazuh.com/current/user-manual/ruleset/custom.html
custom_attributes:
  wazuh_rule_id: wazuh-80109
  wazuh_level: 2