title: 'Netscreen firewall: configuration changed.'
id: bf11c5c9-0927-5f25-8536-39bd616c9f1c
status: stable
level: medium
description: 'Netscreen firewall: configuration changed.'
author: Wazuh, Inc.
logsource:
  product: wazuh
detection:
  selection:
    message|exists: true
  condition: selection

# Sigma+ Extensions (for advanced detection)
extensions:
  parent_rule: wazuh-4504
tags:
  - attack.t1089
references:
  - https://github.com/wazuh/wazuh
  - https://documentation.wazuh.com/current/user-manual/ruleset/custom.html
custom_attributes:
  wazuh_rule_id: wazuh-4509
  wazuh_level: 8