title: 'Netscaler: ICA application has terminated'
id: de4645de-7b01-52e3-babc-99ec9bce3cdf
status: stable
level: informational
description: 'Netscaler: ICA application has terminated'
author: Wazuh, Inc.
logsource:
  product: wazuh
detection:
  selection:
    message|contains: SSLVPN ICAEND_CONNSTAT
  condition: selection

# Sigma+ Extensions (for advanced detection)
extensions:
  parent_rule: wazuh-80100
references:
  - https://github.com/wazuh/wazuh
  - https://documentation.wazuh.com/current/user-manual/ruleset/custom.html
custom_attributes:
  wazuh_rule_id: wazuh-80110
  wazuh_level: 2