title: 'OpenSCAP ERROR: Wrong configuration - Inexistent policy.'
id: 864d2096-4863-5aec-9bf2-df60bc8df997
status: stable
level: medium
description: 'OpenSCAP ERROR: Wrong configuration - Inexistent policy.'
author: Wazuh, Inc.
logsource:
  product: wazuh
detection:
  selection:
    message|contains: ': File "'
  condition: selection

# Sigma+ Extensions (for advanced detection)
extensions:
  parent_rule: wazuh-81501
references:
  - https://github.com/wazuh/wazuh
  - https://documentation.wazuh.com/current/user-manual/ruleset/custom.html
custom_attributes:
  wazuh_rule_id: wazuh-81504
  wazuh_level: 7