title: 'OpenSCAP ERROR: Wrong configuration - Inexistent profile.'
id: 87ff2c4b-016c-5620-9130-dbb79a8bc3a2
status: stable
level: medium
description: 'OpenSCAP ERROR: Wrong configuration - Inexistent profile.'
author: Wazuh, Inc.
logsource:
  product: wazuh
detection:
  selection:
    message|contains: Profile
  condition: selection

# Sigma+ Extensions (for advanced detection)
extensions:
  parent_rule: wazuh-81501
references:
  - https://github.com/wazuh/wazuh
  - https://documentation.wazuh.com/current/user-manual/ruleset/custom.html
custom_attributes:
  wazuh_rule_id: wazuh-81507
  wazuh_level: 7