title: 'osquery: $(osquery.pack) $(osquery.subquery): Application Layer Firewall for OSX version $(osquery.columns.version)'
id: e9922b93-2272-5b3b-897d-77a1369c899f
status: stable
level: low
description: 'osquery: $(osquery.pack) $(osquery.subquery): Application Layer Firewall for OSX version $(osquery.columns.version)'
author: Wazuh, Inc.
logsource:
  product: wazuh
detection:
  selection:
    osquery.name: alf
  condition: selection

# Sigma+ Extensions (for advanced detection)
extensions:
  parent_rule: wazuh-24030
references:
  - https://github.com/wazuh/wazuh
  - https://documentation.wazuh.com/current/user-manual/ruleset/custom.html
custom_attributes:
  wazuh_rule_id: wazuh-24038
  wazuh_level: 4