title: 'osquery: $(osquery.pack) $(osquery.subquery): Application Layer Firewall for OSX service $(osquery.columns.service) state $(osquery.columns.state)'
id: ec67d7e9-b9d1-5143-a99e-6fb192adae00
status: stable
level: low
description: 'osquery: $(osquery.pack) $(osquery.subquery): Application Layer Firewall for OSX service $(osquery.columns.service) state $(osquery.columns.state)'
author: Wazuh, Inc.
logsource:
  product: wazuh
detection:
  selection:
    osquery.name: alf_services
  condition: selection

# Sigma+ Extensions (for advanced detection)
extensions:
  parent_rule: wazuh-24030
references:
  - https://github.com/wazuh/wazuh
  - https://documentation.wazuh.com/current/user-manual/ruleset/custom.html
custom_attributes:
  wazuh_rule_id: wazuh-24041
  wazuh_level: 4