title: 'osquery: $(osquery.pack) $(osquery.subquery): Application Layer Firewall for OSX service $(osquery.columns.service) state $(osquery.columns.state)'
id: 8eb9d18b-8d4f-55dc-bfb5-9217109d8f6e
status: stable
level: low
description: 'osquery: $(osquery.pack) $(osquery.subquery): Application Layer Firewall for OSX service $(osquery.columns.service) state $(osquery.columns.state)'
author: Wazuh, Inc.
logsource:
  product: wazuh
detection:
  selection:
    osquery.name: alf_services
  condition: selection

# Sigma+ Extensions (for advanced detection)
extensions:
  parent_rule: wazuh-24100
references:
  - https://github.com/wazuh/wazuh
  - https://documentation.wazuh.com/current/user-manual/ruleset/custom.html
custom_attributes:
  wazuh_rule_id: wazuh-24108
  wazuh_level: 4