title: 'osquery: $(osquery.pack) $(osquery.subquery): Application Layer Firewall for OSX service exceptions path $(osquery.columns.path)'
id: fcfc8c4a-eb5e-540e-9a24-6c95bc744ffc
status: stable
level: low
description: 'osquery: $(osquery.pack) $(osquery.subquery): Application Layer Firewall for OSX service exceptions path $(osquery.columns.path)'
author: Wazuh, Inc.
logsource:
  product: wazuh
detection:
  selection:
    osquery.name: alf_exceptions
  condition: selection

# Sigma+ Extensions (for advanced detection)
extensions:
  parent_rule: wazuh-24030
references:
  - https://github.com/wazuh/wazuh
  - https://documentation.wazuh.com/current/user-manual/ruleset/custom.html
custom_attributes:
  wazuh_rule_id: wazuh-24040
  wazuh_level: 4