title: 'osquery: $(osquery.pack) $(osquery.subquery): OS X Application $(osquery.columns.name) version $(osquery.columns.bundle_version) is installed'
id: 66909463-62d3-5f2f-9221-005c156a0244
status: stable
level: low
description: 'osquery: $(osquery.pack) $(osquery.subquery): OS X Application $(osquery.columns.name) version $(osquery.columns.bundle_version) is installed'
author: Wazuh, Inc.
logsource:
  product: wazuh
detection:
  selection:
    osquery.name: installed_applications
  condition: selection

# Sigma+ Extensions (for advanced detection)
extensions:
  parent_rule: wazuh-24300
references:
  - https://github.com/wazuh/wazuh
  - https://documentation.wazuh.com/current/user-manual/ruleset/custom.html
custom_attributes:
  wazuh_rule_id: wazuh-24305
  wazuh_level: 4