title: 'osquery: $(osquery.pack) $(osquery.subquery): Application Layer Firewall for OSX version $(osquery.columns.version)'
id: a03ea1ef-8299-5435-951b-79d5ea0ca6ee
status: stable
level: low
description: 'osquery: $(osquery.pack) $(osquery.subquery): Application Layer Firewall for OSX version $(osquery.columns.version)'
author: Wazuh, Inc.
logsource:
  product: wazuh
detection:
  selection:
    osquery.name: alf
  condition: selection

# Sigma+ Extensions (for advanced detection)
extensions:
  parent_rule: wazuh-24100
references:
  - https://github.com/wazuh/wazuh
  - https://documentation.wazuh.com/current/user-manual/ruleset/custom.html
custom_attributes:
  wazuh_rule_id: wazuh-24105
  wazuh_level: 4