title: PAM misconfiguration.
id: 8a3d5428-bce7-5140-8df6-858d7dff6ea5
status: stable
level: low
description: PAM misconfiguration.
author: Wazuh, Inc.
logsource:
  product: wazuh
detection:
  selection:
    message|contains: 'illegal module type:'
  condition: selection
references:
  - https://github.com/wazuh/wazuh
  - https://documentation.wazuh.com/current/user-manual/ruleset/custom.html
custom_attributes:
  wazuh_rule_id: wazuh-5554
  wazuh_level: 4