title: PAM misconfiguration.
id: bd71e011-869d-560c-ad60-15997fd86810
status: stable
level: low
description: PAM misconfiguration.
author: Wazuh, Inc.
logsource:
  product: wazuh
detection:
  selection:
    message|contains: 'cannot open shared object file: No such file or directory'
  condition: selection
references:
  - https://github.com/wazuh/wazuh
  - https://documentation.wazuh.com/current/user-manual/ruleset/custom.html
custom_attributes:
  wazuh_rule_id: wazuh-5553
  wazuh_level: 4