title: 'PIX: Firewall configuration deleted.'
id: a6af7292-03ee-5a9f-84d5-f856443dd79b
status: stable
level: medium
description: 'PIX: Firewall configuration deleted.'
author: Wazuh, Inc.
logsource:
  product: wazuh
detection:
  selection:
    message|exists: true
  condition: selection

# Sigma+ Extensions (for advanced detection)
extensions:
  parent_rule: wazuh-4314
tags:
  - attack.t1089
references:
  - https://github.com/wazuh/wazuh
  - https://documentation.wazuh.com/current/user-manual/ruleset/custom.html
custom_attributes:
  wazuh_rule_id: wazuh-4339
  wazuh_level: 8