title: 'proftpd: Small PassivePorts range in config file.'
id: e818ac26-e95a-57b1-adc5-e4a2e1d26614
status: stable
level: low
description: 'proftpd: Small PassivePorts range in config file.'
author: Wazuh, Inc.
logsource:
  product: wazuh
detection:
  selection:
    message|contains: unable to find open port in PassivePorts range
  condition: selection

# Sigma+ Extensions (for advanced detection)
extensions:
  parent_rule: wazuh-11200
references:
  - https://github.com/wazuh/wazuh
  - https://documentation.wazuh.com/current/user-manual/ruleset/custom.html
custom_attributes:
  wazuh_rule_id: wazuh-11208
  wazuh_level: 4