title: 'proftpd: Reverse lookup error (bad ISP config).'
id: 4d8e822e-a6ad-5a83-846c-ac961cddf456
status: stable
level: low
description: 'proftpd: Reverse lookup error (bad ISP config).'
author: Wazuh, Inc.
logsource:
  product: wazuh
detection:
  selection:
    message|contains: 'warning: can''t verify hostname:'
  condition: selection

# Sigma+ Extensions (for advanced detection)
extensions:
  parent_rule: wazuh-11200
references:
  - https://github.com/wazuh/wazuh
  - https://documentation.wazuh.com/current/user-manual/ruleset/custom.html
custom_attributes:
  wazuh_rule_id: wazuh-11212
  wazuh_level: 5