title: 'Samba: User action denied by configuration.'
id: 96652102-706b-56a0-8b14-10d3758663bf
status: stable
level: low
description: 'Samba: User action denied by configuration.'
author: Wazuh, Inc.
logsource:
  product: wazuh
detection:
  selection:
    message|contains: Permission denied--
  condition: selection

# Sigma+ Extensions (for advanced detection)
extensions:
  parent_rule: wazuh-13100
references:
  - https://github.com/wazuh/wazuh
  - https://documentation.wazuh.com/current/user-manual/ruleset/custom.html
custom_attributes:
  wazuh_rule_id: wazuh-13104
  wazuh_level: 5