title: Service started application version
id: 8451eb63-df69-5b68-bc7e-4993a03f4b49
status: stable
level: low
description: Service started application version
author: Wazuh, Inc.
logsource:
  product: wazuh
detection:
  selection:
    win.system.eventID: ^4099$
  condition: selection

# Sigma+ Extensions (for advanced detection)
extensions:
  parent_rule: wazuh-60600
references:
  - https://github.com/wazuh/wazuh
  - https://documentation.wazuh.com/current/user-manual/ruleset/custom.html
custom_attributes:
  wazuh_rule_id: wazuh-90502
  wazuh_level: 3