title: Syntax error in a named configuration file.
id: b8c29bf2-b958-56b0-a9bb-08ca47c7db68
status: stable
level: informational
description: Syntax error in a named configuration file.
author: Wazuh, Inc.
logsource:
  product: wazuh
detection:
  selection:
    message|contains:
      - syntax error near
  condition: selection

# Sigma+ Extensions (for advanced detection)
extensions:
  parent_rule: wazuh-12100
references:
  - https://github.com/wazuh/wazuh
  - https://documentation.wazuh.com/current/user-manual/ruleset/custom.html
custom_attributes:
  wazuh_rule_id: wazuh-12116
  wazuh_level: 1