title: 'System Audit: Vulnerable web application found.'
id: 4c05492c-70af-5049-ae54-bd3ab1fb7b95
status: stable
level: medium
description: 'System Audit: Vulnerable web application found.'
author: Wazuh, Inc.
logsource:
  product: wazuh
detection:
  selection:
    message|contains: '^System Audit: Web vulnerability'
  condition: selection

# Sigma+ Extensions (for advanced detection)
extensions:
  parent_rule: wazuh-516
references:
  - https://github.com/wazuh/wazuh
  - https://documentation.wazuh.com/current/user-manual/ruleset/custom.html
custom_attributes:
  wazuh_rule_id: wazuh-519
  wazuh_level: 7