title: 'telnetd: Reverse lookup error (bad hostname config).'
id: 705904ec-e4b7-581c-ae48-e525debef6c4
status: stable
level: low
description: 'telnetd: Reverse lookup error (bad hostname config).'
author: Wazuh, Inc.
logsource:
  product: wazuh
detection:
  selection:
    message|contains: 'warning: can''t verify hostname:'
  condition: selection
references:
  - https://github.com/wazuh/wazuh
  - https://documentation.wazuh.com/current/user-manual/ruleset/custom.html
custom_attributes:
  wazuh_rule_id: wazuh-5604
  wazuh_level: 5