title: 'The resource was deleted. AWS Config - History:  [$(aws.awsAccountId) $(aws.awsRegion)] [$(aws.resourceType)]: $(aws.resourceId) ($(aws.configurationI'
id: 97c051cb-03a8-5fdd-a331-d0deadbb4042
status: stable
level: low
description: 'The resource was deleted. AWS Config - History:  [$(aws.awsAccountId) $(aws.awsRegion)] [$(aws.resourceType)]: $(aws.resourceId) ($(aws.configurationItemStatus))'
author: Wazuh, Inc.
logsource:
  product: wazuh
detection:
  selection:
    aws.configurationItemStatus: ResourceDeleted
  condition: selection

# Sigma+ Extensions (for advanced detection)
extensions:
  parent_rule: wazuh-80451
references:
  - https://github.com/wazuh/wazuh
  - https://documentation.wazuh.com/current/user-manual/ruleset/custom.html
custom_attributes:
  wazuh_rule_id: wazuh-80456
  wazuh_level: 3