title: The resource was discovered but its configuration was not recorded since the recorder excludes the recording of resources of this type. AWS Config - H
id: 293b3924-1886-5bb4-8da6-e494b3ad4ff4
status: stable
level: low
description: |
  The resource was discovered but its configuration was not recorded since the recorder excludes the recording of resources of this type. AWS Config - History:  [$(aws.awsAccountId) $(aws.awsRegion)] [$(aws.resourceType)]: $(aws.resourceId) ($(aws.configurationItemStatus))
author: Wazuh, Inc.
logsource:
  product: wazuh
detection:
  selection:
    aws.configurationItemStatus: ResourceNotRecorded
  condition: selection

# Sigma+ Extensions (for advanced detection)
extensions:
  parent_rule: wazuh-80451
references:
  - https://github.com/wazuh/wazuh
  - https://documentation.wazuh.com/current/user-manual/ruleset/custom.html
custom_attributes:
  wazuh_rule_id: wazuh-80455
  wazuh_level: 3