title: Virtual machine being reconfigured.
id: 3ff79c26-d5b9-5986-869f-8af5630ebd5d
status: stable
level: low
description: Virtual machine being reconfigured.
author: Wazuh, Inc.
logsource:
  product: wazuh
detection:
  selection:
    message|contains: '-> VM_STATE_RECONFIGURING'
  condition: selection

# Sigma+ Extensions (for advanced detection)
extensions:
  parent_rule: wazuh-19106
references:
  - https://github.com/wazuh/wazuh
  - https://documentation.wazuh.com/current/user-manual/ruleset/custom.html
custom_attributes:
  wazuh_rule_id: wazuh-19123
  wazuh_level: 5