title: Windows application monitor event.
id: 90e5a03f-cdc5-58c7-a98d-874db822cee9
status: stable
level: informational
description: Windows application monitor event.
author: Wazuh, Inc.
logsource:
  product: wazuh
detection:
  selection:
    message|contains: ^Application Found
  condition: selection

# Sigma+ Extensions (for advanced detection)
extensions:
  parent_rule: wazuh-510
references:
  - https://github.com/wazuh/wazuh
  - https://documentation.wazuh.com/current/user-manual/ruleset/custom.html
custom_attributes:
  wazuh_rule_id: wazuh-514
  wazuh_level: 2