version: '1.0'
vendor: Traefik
product: Proxy
product_full_name: Proxy
log_type: structured
source_document: ''
source_url: ''
extraction_date: '2026-01-29'
source_file: traefik-proxy-signatures.json
generated_at: '2026-01-29T05:59:01.678457'
field_count: 0
fields: []
signatures:
- name: traefik_access
  description: Traefik access log
  pattern: traefik\.access|traefik.*access
  event_type: http
  confidence: 0.95
