title: AWS Config Service Modified
id: d2e3a0d5-7c83-5e34-b0d0-88eadb095179
status: experimental
level: high
description: Detects when AWS Config Service is updated, stopped or deleted.
author: Google Cloud Security
logsource:
  product: aws
detection:
  selection:
    metadata_vendor_name: AMAZON
    metadata_product_name: AWS CloudTrail
    metadata_product_event_type:
      - StopConfigurationRecorder
      - DeleteConfigurationRecorder
      - DeleteDeliveryChannel
      - PutDeliveryChannel
      - PutConfigurationRecorder
    security_result_action: ALLOW
  condition: selection
tags:
  - attack.t1562
custom_attributes:
  original_rule_id: mr_9a5af6d7-5119-46db-ad24-72d7e873a56b
  source_format: chronicle_yaral