title: Client Secret Added to Entra ID Application
id: fb7402f6-07b0-50cf-857f-1b368e243168
status: experimental
level: medium
description: Secrets added to applications have legitimate purposes, but can also be a method of persistence.
author: Google Cloud Security
logsource:
  product: azure
detection:
  selection:
    metadata_event_type: SERVICE_MODIFICATION
    metadata_product_name: Azure AD Directory Audit
    metadata_vendor_name: Microsoft
    security_result_action: ALLOW
    metadata_product_event_type: Update application.*Certificates and secrets management
  condition: selection
custom_attributes:
  original_rule_id: mr_22d3881f-f84d-42ee-a1bc-5d5eb419b769
  source_format: chronicle_yaral