title: Entra ID Application Restore
id: 86fac93d-0b21-55c4-8b74-7586de0e6d58
status: experimental
level: medium
description: |
  Entra ID application was restored. This implies a soft delete was performed at some point but less than 30 days ago.
author: Google Cloud Security
logsource:
  product: azure
detection:
  selection:
    metadata_event_type: SERVICE_CREATION
    metadata_product_event_type: Restore application
    metadata_product_name: Azure AD Directory Audit
    metadata_vendor_name: Microsoft
    security_result_action: ALLOW
  condition: selection
custom_attributes:
  original_rule_id: mr_ed0a04f9-4ceb-499e-9e6f-01e4507b8da5
  source_format: chronicle_yaral