title: Entra ID Application Deletion
id: 15581bd3-72e2-5fdd-b7a4-79cb85ab8dcc
status: experimental
level: medium
description: Delete Entra ID application. This is a soft delete, can still be recovered.
author: Google Cloud Security
logsource:
  product: azure
detection:
  selection:
    metadata_event_type: SETTING_DELETION
    metadata_product_event_type: Delete application
    metadata_product_name: Azure AD Directory Audit
    metadata_vendor_name: Microsoft
    security_result_action: ALLOW
  condition: selection
custom_attributes:
  original_rule_id: mr_597d57bf-1bae-4179-a068-7985c2d28340
  source_format: chronicle_yaral