title: Entra ID Application Hard Deletion
id: f4cb09fd-bba4-5b24-9260-8c7f4c40dd67
status: experimental
level: medium
description: Deletion of Entra ID application with no recovery of the application.
author: Google Cloud Security
logsource:
  product: azure
detection:
  selection:
    metadata_event_type: SETTING_DELETION
    metadata_product_event_type: Hard Delete application
    metadata_product_name: Azure AD Directory Audit
    metadata_vendor_name: Microsoft
    security_result_action: ALLOW
  condition: selection
custom_attributes:
  original_rule_id: mr_b4b8a401-4803-498a-b601-d984cf5042fa
  source_format: chronicle_yaral