title: GitHub OAuth Application Access Restrictions Disabled
id: fb79f4b0-8627-5331-ab48-d745e29ab73c
status: experimental
level: low
description: Detects when third-party application access restrictions are disabled for a GitHub organization.
author: Google Cloud Security
logsource:
  product: github
  category: authentication
detection:
  selection:
    metadata_vendor_name: GITHUB
    metadata_product_name: GITHUB
    metadata_product_event_type: org.disable_oauth_app_restrictions
  condition: selection
references:
  - https://docs.github.com/en/enterprise-cloud@latest/admin/monitoring-activity-in-your-enterprise/reviewing-audit-logs-for-your-enterprise/audit-log-events-for-your-enterprise
custom_attributes:
  original_rule_id: mr_9faa8dae-8e9f-4c10-9d11-e45eaebe1070
  source_format: chronicle_yaral