title: GitHub Dependabot Vulnerability Alerts Disabled
id: cb6a8b55-f45b-5d2b-b77a-e4272f6e8afc
status: experimental
level: high
description: Detects when vulnerability alerts are disabled for GitHub Dependabot.
author: Google Cloud Security
logsource:
  product: github
detection:
  selection:
    metadata_vendor_name: GITHUB
    metadata_product_name: GITHUB
    metadata_product_event_type:
      - repository_vulnerability_alerts.disable
      - business_dependabot_alerts.disable
      - business_dependabot_alerts_new_repos.disable
      - dependabot_alerts.disable
      - dependabot_alerts_new_repos.disable
      - dependabot_security_updates.disable
      - dependabot_security_updates_new_repos.disable
  condition: selection
tags:
  - attack.t1562
references:
  - https://docs.github.com/en/enterprise-cloud@latest/admin/monitoring-activity-in-your-enterprise/reviewing-audit-logs-for-your-enterprise/audit-log-events-for-your-enterprise
custom_attributes:
  original_rule_id: mr_fe479d25-26d1-4eef-b22d-fd1a0e9fdd86
  source_format: chronicle_yaral