title: Google Workspace SAML IDP Configuration Change
id: aa4fb34b-3eb1-5742-917d-9c20834d49a2
status: experimental
level: high
description: |
  Identifies SAML provider configuration changes in Google Workspace. Security teams can monitor for changes to SAML provider configuration that may weaken the organization's security posture.
author: Google Cloud Security
logsource:
  product: gcp
detection:
  selection:
    metadata_vendor_name: Google Workspace
    metadata_product_name: admin
    security_result_category_details: SAML2_SERVICE_PROVIDER_CONFIG_SETTINGS
    metadata_product_event_type: SAML2_SERVICE_PROVIDER_CONFIG
  condition: selection
tags:
  - attack.t1078
custom_attributes:
  original_rule_id: mr_1a321683-9c52-4928-a654-e0677df97c09
  source_format: chronicle_yaral