title: Google Workspace Application Added
id: 77a1946b-fd3b-5042-8835-77ff30638881
status: experimental
level: high
description: |
  Identifies when a Marketplace app is added in a Google Workspace organization. Installing certain apps may increase the organization's risk of data exfiltration/leakage and increase its attack surface.
author: Google Cloud Security
logsource:
  product: gcp
detection:
  selection:
    metadata_vendor_name: Google Workspace
    metadata_product_name: admin
    metadata_product_event_type: ADD_APPLICATION
  condition: selection
custom_attributes:
  original_rule_id: mr_bb4f5ff0-76b8-4b08-8b1b-fcb81e5a10cc
  source_format: chronicle_yaral