title: OneLogin Application Password Revealed
id: 79d50740-22b9-54b2-af3a-36c265c6ce86
status: experimental
level: high
description: Detects when a user revealed another user's application password.
author: Google Cloud Security
logsource:
  product: gcp
  category: authentication
detection:
  selection:
    metadata_event_type: USER_RESOURCE_ACCESS
    metadata_product_name: ONELOGIN_SSO
    metadata_vendor_name: ONELOGIN
    metadata_product_event_type: 240
  condition: selection
tags:
  - attack.t1552
references:
  - https://onelogin.service-now.com/kb_view_customer.do?sysparm_article=KB0010598
custom_attributes:
  original_rule_id: mr_785c2d0e-067e-4ad6-a27b-91d0af644718
  source_format: chronicle_yaral