title: Recon Environment Enumeration System CISA Report
id: 65e933d5-6b1a-50b3-ab0f-849a4c47663f
status: experimental
level: low
description: |
  Detects system enumeration events as identified in CISA Living off the Land pdf. Alone they may be normal but in concert, they may be worth looking into
author: Google Cloud Security
logsource:
  product: gcp
detection:
  selection:
    metadata_event_type: PROCESS_LAUNCH
  condition: selection
references:
  - https://media.defense.gov/2023/May/24/2003229517/-1/-1/0/CSA_Living_off_the_Land.PDF
custom_attributes:
  original_rule_id: mr_086dede6-33ba-42df-b001-5595ceb0d589
  source_format: chronicle_yaral