title: Recon Environment Enumeration Network CISA Report
id: 19769b27-1127-5109-a9be-92a53fe540fb
status: experimental
level: low
description: |
  Detects network enumeration commands as identified in CISA Living off the Land pdf. Alone they may be normal but in concert, they may be worth looking into
author: Google Cloud Security
logsource:
  product: gcp
  category: network_connection
detection:
  selection:
    metadata_event_type:
      - PROCESS_LAUNCH
      - NETWORK_DNS
    network_application_protocol: DNS
    network_dns_questions_name: www.ip-api.com
  condition: selection
references:
  - https://media.defense.gov/2023/May/24/2003229517/-1/-1/0/CSA_Living_off_the_Land.PDF
custom_attributes:
  original_rule_id: mr_9ca49a46-fb60-4ada-b722-5714d5cb7f53
  source_format: chronicle_yaral