title: Recon Environment Enumeration Active Directory CISA Report
id: e20d9fe2-bf08-56e5-be57-8b7903cfa565
status: experimental
level: low
description: |
  Detects group enumeration commands as identified in CISA Living off the Land pdf. Alone they may be normal but in concert, they may be worth looking into
author: Google Cloud Security
logsource:
  product: gcp
detection:
  selection:
    metadata_event_type: PROCESS_LAUNCH
  condition: selection
references:
  - https://media.defense.gov/2023/May/24/2003229517/-1/-1/0/CSA_Living_off_the_Land.PDF
custom_attributes:
  original_rule_id: mr_f7609336-c490-4601-bb75-1a1a142ad1cd
  source_format: chronicle_yaral