vendor: Kubernetes
product: API Server Audit Logs
product_full_name: Kubernetes API Server Audit Logs
field_count: 34
last_updated: '2026-01-08'
source: siemless_v3_database
fields:
- field_name: annotations
  data_type: object
  description: Unstructured key-value map set by plugins in the request serving chain
  universal_field_path: null
  required: false
  example_values: []
- field_name: apiVersion
  data_type: string
  description: API version (audit.k8s.io/v1)
  universal_field_path: null
  required: false
  example_values: []
- field_name: auditID
  data_type: string
  description: Unique audit ID generated for each request
  universal_field_path: null
  required: false
  example_values: []
- field_name: authenticationMetadata.impersonationConstraint
  data_type: string
  description: The verb associated with constrained impersonation mode
  universal_field_path: null
  required: false
  example_values: []
- field_name: impersonatedUser.groups
  data_type: array
  description: Groups of the impersonated user
  universal_field_path: null
  required: false
  example_values: []
- field_name: impersonatedUser.uid
  data_type: string
  description: UID of the impersonated user
  universal_field_path: null
  required: false
  example_values: []
- field_name: impersonatedUser.username
  data_type: string
  description: Username of the impersonated user
  universal_field_path: null
  required: false
  example_values: []
- field_name: kind
  data_type: string
  description: Resource kind (Event)
  universal_field_path: null
  required: false
  example_values: []
- field_name: level
  data_type: enum
  description: Audit level at which event was generated (None, Metadata, Request,
    RequestResponse)
  universal_field_path: null
  required: false
  example_values: []
- field_name: objectRef.apiGroup
  data_type: string
  description: Name of the API group (empty string = core API group)
  universal_field_path: null
  required: false
  example_values: []
- field_name: objectRef.apiVersion
  data_type: string
  description: Version of the API group
  universal_field_path: null
  required: false
  example_values: []
- field_name: objectRef.name
  data_type: string
  description: Name of the object
  universal_field_path: null
  required: false
  example_values: []
- field_name: objectRef.namespace
  data_type: string
  description: Namespace of the object
  universal_field_path: null
  required: false
  example_values: []
- field_name: objectRef.resource
  data_type: string
  description: Resource kind (pods, deployments, services, etc.)
  universal_field_path: null
  required: false
  example_values: []
- field_name: objectRef.resourceVersion
  data_type: string
  description: Resource version of the object
  universal_field_path: null
  required: false
  example_values: []
- field_name: objectRef.subresource
  data_type: string
  description: Subresource name (status, scale, etc.)
  universal_field_path: null
  required: false
  example_values: []
- field_name: objectRef.uid
  data_type: string
  description: Unique identifier of the object
  universal_field_path: null
  required: false
  example_values: []
- field_name: requestObject
  data_type: object
  description: API object from the request in JSON format
  universal_field_path: null
  required: false
  example_values: []
- field_name: requestReceivedTimestamp
  data_type: datetime
  description: Time the request reached the API server (MicroTime)
  universal_field_path: null
  required: false
  example_values: []
- field_name: requestURI
  data_type: string
  description: The request URI as sent by the client to the server
  universal_field_path: null
  required: false
  example_values: []
- field_name: responseObject
  data_type: object
  description: API object returned in the response in JSON format
  universal_field_path: null
  required: false
  example_values: []
- field_name: responseStatus.code
  data_type: integer
  description: HTTP status code of the response
  universal_field_path: null
  required: false
  example_values: []
- field_name: responseStatus.message
  data_type: string
  description: Human-readable description of the status
  universal_field_path: null
  required: false
  example_values: []
- field_name: responseStatus.reason
  data_type: string
  description: Machine-readable reason for the status
  universal_field_path: null
  required: false
  example_values: []
- field_name: responseStatus.status
  data_type: string
  description: Status of the operation (Success, Failure)
  universal_field_path: null
  required: false
  example_values: []
- field_name: sourceIPs
  data_type: array
  description: Source IPs from where the request originated and intermediate proxies
  universal_field_path: null
  required: false
  example_values: []
- field_name: stage
  data_type: enum
  description: Stage of request handling when event was generated
  universal_field_path: null
  required: false
  example_values: []
- field_name: stageTimestamp
  data_type: datetime
  description: Time the request reached current audit stage (MicroTime)
  universal_field_path: null
  required: false
  example_values: []
- field_name: userAgent
  data_type: string
  description: User agent string reported by the client
  universal_field_path: null
  required: false
  example_values: []
- field_name: user.extra
  data_type: object
  description: Any additional information provided by the authenticator
  universal_field_path: null
  required: false
  example_values: []
- field_name: user.groups
  data_type: array
  description: The names of groups this user is a part of
  universal_field_path: null
  required: false
  example_values: []
- field_name: user.uid
  data_type: string
  description: A unique value that identifies this user across time
  universal_field_path: null
  required: false
  example_values: []
- field_name: user.username
  data_type: string
  description: The name that uniquely identifies this user
  universal_field_path: null
  required: false
  example_values: []
- field_name: verb
  data_type: string
  description: Kubernetes verb associated with the request (get, list, create, update,
    delete, etc.)
  universal_field_path: null
  required: false
  example_values: []
